name: 'CI'

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request: #necessary to display "check" step in a PR
  workflow_dispatch: #manual execution only

jobs:
  placeholder:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check tag display
        run: echo "[x] CI ready to run manually"

  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        smalltalk: [ Pharo64-11, Pharo64-12, Pharo64-13 ]
        ston: [ .smalltalkci.default.ston ]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    name: >
      ${{ matrix.smalltalk }} • ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}

      - name: Run ${{ matrix.ston == '.smalltalkci.default.ston' && 'Full' || 'Core' }} tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        timeout-minutes: 30